name: 'Workflow na selfhosted'
on:
  workflow_dispatch:

jobs:
  test_selfhosted:
    runs-on: self-hosted
    steps:
      - name: 'I am alive'
        run: echo 'Selfhosted script started successfully'
      - name: 'Just grep'
        run: findstr "hqr"  C:\Users\jakub\Desktop\Robocze\GA\KursGithubActions\.github\workflows\actionsDemo\file.txt
 
