name: 'Workflow na selfhosted'
on:
  workflow_dispatch:

jobs:
  test_selfhosted:
    runs-on: self-hosted
    steps:
      - name: 'I am alive'
        run: echo 'Selfhosted script started successfully'
      - name: 'Just grep'
        run: FIND 'hqr' /actionsDemo/file.txt 
